/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/c82o01Ato4e
 */
import { Button } from "@/components/ui/button"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { Separator } from "@/components/ui/separator"

export function FAQ() {
  return (
    <section className="w-full py-12">
      <div className="container px-4 md:px-6">
        <div className="max-w-3xl space-y-8 md:space-y-10 lg:space-y-12">
          <div className="space-y-2">
            <h2 className="text-gray-100 dark:text-gray-100 font-bold text-8xl font-bold tracking-tighter sm:text-6xl ">FAQ</h2>
            <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed dark:text-gray-400">
              Got a question? We've got answers. If you have some other questions, feel free to send us an email to
              <a href="#">admin@utopia.express</a>
            </p>
          </div>
          <div className="space-y-4">
            <div className="space-y-2">
              <h3 className="text-xl font-bold">How it works the credit system?</h3>
              <Collapsible className="space-y-2">
                <CollapsibleTrigger asChild>
                  <Button
                    className="w-6 h-6 p-1 rounded-full border border-transparent border-gray-200 text-gray-500 transition-colors hover:border-gray-300 hover:text-gray-900 dark:border-gray-800 dark:text-gray-400 dark:hover:border-gray-50 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost"
                  >
                    <ChevronDownIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle</span>
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent asChild>
                  <div className="prose max-w-none">
                    <p>
                      One credit = One custom training with your uploaded photos.
                    </p>
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold">How many photos I get?</h3>
              <Collapsible className="space-y-2">
                <CollapsibleTrigger asChild>
                  <Button
                    className="w-6 h-6 p-1 rounded-full border border-transparent border-gray-200 text-gray-500 transition-colors hover:border-gray-300 hover:text-gray-900 dark:border-gray-800 dark:text-gray-400 dark:hover:border-gray-50 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost"
                  >
                    <ChevronDownIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle</span>
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent asChild>
                  <div className="prose max-w-none">
                    <p>
                      For one credit, you get 21 high quality photos
                    </p>
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold">What if I'm not satisfied?</h3>
              <Collapsible className="space-y-2">
                <CollapsibleTrigger asChild>
                  <Button
                    className="w-6 h-6 p-1 rounded-full border border-transparent border-gray-200 text-gray-500 transition-colors hover:border-gray-300 hover:text-gray-900 dark:border-gray-800 dark:text-gray-400 dark:hover:border-gray-50 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost"
                  >
                    <ChevronDownIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle</span>
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent asChild>
                  <div className="prose max-w-none">
                    <p>
                    Note that the final result depends significantly on the quality of the uploaded images. If you feel that the result is absolutely not the same, no matter how you try, contact us: admin@utopia.express
                    </p>
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold">How can i get the best result?</h3>
              <Collapsible className="space-y-2">
                <CollapsibleTrigger asChild>
                  <Button
                    className="w-6 h-6 p-1 rounded-full border border-transparent border-gray-200 text-gray-500 transition-colors hover:border-gray-300 hover:text-gray-900 dark:border-gray-800 dark:text-gray-400 dark:hover:border-gray-50 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost"
                  >
                    <ChevronDownIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle</span>
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent asChild>
                  <div className="prose max-w-none">
                    <p>
                    Note, that the final result depends significantly on the quality of the uploaded images.
                    <Separator />
                    1 use a variety of lighting
                    <Separator />
                    2. don't grimace
                    <Separator />
                    3. use multiple backgrounds
                    <Separator />
                    4. upload a picture that shows you at least half-length.
                    </p>
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold">Can i get a refund if i'm not satisfied?</h3>
              <Collapsible className="space-y-2">
                <CollapsibleTrigger asChild>
                  <Button
                    className="w-6 h-6 p-1 rounded-full border border-transparent border-gray-200 text-gray-500 transition-colors hover:border-gray-300 hover:text-gray-900 dark:border-gray-800 dark:text-gray-400 dark:hover:border-gray-50 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost"
                  >
                    <ChevronDownIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle</span>
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent asChild>
                  <div className="prose max-w-none">
                    <p>
                    Since this is a very new, experimental technology, and the result is highly subjective, we are unable to refund money. If you feel that the result is absolutely not you, no matter how you try, contact us: admin@utopia.express
                    </p>
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}


function ChevronDownIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
