/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/t8syqPX5YHx
 */
import { Card } from "@/components/ui/card"

export function HowItWoks() {
  return (
    <>
      <Card className="flex w-full items-flex-start border-transparent shadow-none p-4 mt-4">
        <div className="flex items-flex-start justify-center w-32 h-32 rounded-sm text-gray-100 dark:text-gray-100 font-bold text-8xl">
          01
        </div>
        <div className="grid gap-2 ml-6">
          <p className="text-lg font-semibold">Upload your photos</p>
          <p className="text-sm text-gray-500 dark:text-gray-400">
          Upload at least 6-12 pictures of the person you want to clone. Make sure that only you are in the picture and that your face is clearly visible.
          </p>
          <img
            alt="Upload an image"
            className="mt-4 object-cover rounded-lg"
            height="auto"
            src="/example.png"
            style={{
              aspectRatio: "full/auto",
              objectFit: "cover",
            }}
            width="full"
          />
        </div>
      </Card>
      <div className="flex items-center justify-center w-full">
        <div className="h-9 w-0.5 bg-gray-200 dark:bg-gray-800" />
      </div>
      <Card className="flex w-full items-flex-start border-transparent shadow-none p-4 mt-4">
        <div className="flex items-flex-start justify-center w-32 h-32 rounded-lg text-gray-100 dark:text-gray-100 font-bold text-8xl">
          02
        </div>
        <div className="grid gap-2 ml-6">
          <p className="text-lg font-semibold">Do the magic</p>
          <p className="text-sm text-gray-500 dark:text-gray-400">Our AI-based service able "learn" your unique features and reproduce them down to the smallest detail.</p>

        </div>
      </Card>
      <div className="flex items-center justify-center w-full">
        <div className="h-9 w-0.5 bg-gray-200 dark:bg-gray-800" />
      </div>
      <Card className="flex w-full items-flex-start border-transparent shadow-none p-4 mt-4">
        <div className="flex items-flex-start justify-center w-32 h-32 rounded-lg text-gray-100 dark:text-gray-100 font-bold text-8xl">
          03
        </div>
        <div className="grid gap-2 ml-6">
          <p className="text-lg font-semibold">Get your amazing photos</p>
          <p className="text-sm text-gray-500 dark:text-gray-400">With your own model, any picture can be taken of you, as if you had a professional photographer. The only limit is your imagination.</p>

        </div>
      </Card>
    </>
  )
}
