/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/t8syqPX5YHx
 */
import { Card } from "@/components/ui/card";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import Link from "next/link";
export function HowItWoks() {
  return (
    <>
      <Card className="flex w-full items-flex-start shadow-xl p-4 mt-4">
        <div className="flex items-flex-start justify-center w-32 h-32 rounded-sm text-gray-100 dark:text-gray-100 font-bold text-8xl sm:text-4xl">
          01
        </div>
        <div className="grid gap-2 ml-6">
          <p className="text-lg font-semibold">Upload your fu*ked up photos</p>
          <p className="text-sm text-gray-500 dark:text-gray-400">
          Upload at least 6-12 pictures of the person you want to clone. Make sure that only you are in the picture and that your face is clearly visible.
          <HoverCard>
            <HoverCardTrigger>How to get the best result</HoverCardTrigger>
            <HoverCardContent>
              1. 
            </HoverCardContent>
          </HoverCard>

          </p>
          <img
            alt="Upload an image"
            className="mt-4 object-cover rounded-lg"
            height="auto"
            src="/example.png"
            style={{
              aspectRatio: "full/auto",
              objectFit: "cover",
            }}
            width="full"
          />
        <div className="flex items-center">
          <Link
            className="inline-flex w-100 items-center rounded-full shadow-lg hover:shadow-xl bg-blue-50 hover:bg-blue-100 dark:bg-blue-100 text-black-800 text-sm font-normal px-2 py-1 ml-2"
            href="./login"
            style={{
              borderRadius: "50px",
            }}
          >
          <img
            alt="Double helix"
            className="rounded-full mr-2"
            height={34}
            src="/kep2.gif"
            style={{
              aspectRatio: "34/34",
              objectFit: "cover",
            }}
            width={34}
          />
          Get your good-looking portraits&nbsp;&nbsp; 
          </Link>
          <span className="text-sm font-thin"> 21 photo </span><span className="text-lg font-bold opacity-60">12€ </span>
        </div>
        </div>
      </Card>
      <div className="flex items-center justify-center w-full">
        <div className="h-9 w-0.5 bg-gray-200 dark:bg-gray-800" />
      </div>
      <Card className="flex w-full items-flex-start shadow-lg p-4 mt-4">
        <div className="flex items-flex-start justify-center w-32 h-32 rounded-lg text-gray-100 dark:text-gray-100 font-bold text-8xl sm:text-4xl">
          02
        </div>
        <div className="grid gap-2 ml-6">
          <p className="text-lg font-semibold">Do the magic</p>
          <p className="text-sm text-gray-500 dark:text-gray-400">Our AI-based service able "learn" your unique features and reproduce them down to the smallest detail.</p>

        </div>
      </Card>
      <div className="flex items-center justify-center w-full">
        <div className="h-9 w-0.5 bg-gray-200 dark:bg-gray-800" />
      </div>
      <Card className="flex w-full items-flex-start shadow-lg p-4 mt-4">
        <div className="flex items-flex-start justify-center w-32 h-32 rounded-lg text-gray-100 dark:text-gray-100 font-bold text-8xl sm:text-4xl">
          03
        </div>
        <div className="grid gap-2 ml-6">
          <p className="text-lg font-semibold">Get your amazing photos</p>
          <p className="text-sm text-gray-500 dark:text-gray-400">With your own model, any picture can be taken of you, as if you had a professional photographer. The only limit is your imagination.</p>

        </div>
      </Card>
    </>
  )
}
