/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GvJ50E05JIq
 */
import Link from "next/link";
import { Badge } from "@/components/ui/badge";

export function MainHero() {
  return (
    <section className="w-full">
      <div className="container px-4 md:px-6 flex flex-col items-start gap-2">
        <h1 className="pt-5 text-5xl font-extrabold tracking-tighter lg:text-6xl">Have a good photo of you</h1>
        <p className="py-2 text-lg max-w-[700px] text-gray-500 dark:text-gray-400">
        Create your digital clone, and take good looking photos of you.
        No filters, no makeup, it's you, in your perfect form.
        </p>
        <div className="flex items-center">
          <Link
            className="inline-flex w-100 items-center rounded-full shadow-blue-500/50 shadow-lg hover:shadow-xl bg-slate-800 hover:bg-slate-800 dark:bg-slate-800 text-slate-100	 text-sm font-normal px-2 py-1 ml-2"
            href="./login"
            style={{
              borderRadius: "50px",
            }}
          >
          <img
            alt="Double helix"
            className="rounded-full mr-2"
            height={34}
            src="/kep2.gif"
            style={{
              aspectRatio: "34/34",
              objectFit: "cover",
            }}
            width={34}
          />
          Get your good-looking portraits&nbsp;&nbsp; 
          </Link>
          <span className="text-sm font-thin"> 21 photo </span><span className="text-lg font-bold opacity-60">12€ </span>
        </div>
      </div>
    </section>
  )
}
